In [1]:
# 1. Write a Python Program to Add Two Matrices?

import numpy as np
a = np.mat(np.array([[1,2],[3,4]]))
print("The Matrix A is :- \n",a)
b = np.mat(np.array([[5,6],[7,8]]))
print("The Matrix B is :- \n",b)
print("The Addition of Two Matrices is :- \n",a + b)

The Matrix A is :- 
 [[1 2]
 [3 4]]
The Matrix B is :- 
 [[5 6]
 [7 8]]
The Addition of Two Matrices is :- 
 [[ 6  8]
 [10 12]]


In [2]:
# 2. Write a Python Program to Multiply Two Matrices?

import numpy as np
a = np.mat(np.array([[1,2],[3,4]]))
print("The Matrix A is :- \n",a)
b = np.mat(np.array([[5,6],[7,8]]))
print("The Matrix B is :- \n",b)
print("The Addition of Two Matrices is :- \n",a @ b)

The Matrix A is :- 
 [[1 2]
 [3 4]]
The Matrix B is :- 
 [[5 6]
 [7 8]]
The Addition of Two Matrices is :- 
 [[19 22]
 [43 50]]


In [3]:
# 3. Write a Python Program to Transpose a Matrix?

matrix = np.mat(np.array([[[1,2,3],[4,5,6],[7,8,9]]]))
print("The Original Matrix is :- \n",matrix)
print("The Transpose is :- \n",matrix.T)

The Original Matrix is :- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The Transpose is :- 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

def sort_word(word):
    print("Original Word :-\n",word,sep="")
    a = list(word)
    a.sort()
    print("In Sorted Manner :-\n",*a,sep='')

sort_word(input("Enter the string :-"))    

Enter the string :-chaudhari
Original Word :-
chaudhari
In Sorted Manner :-
aacdhhiru


In [5]:
# 5. Write a Python Program to Remove Punctuation From a String?

string = input("Enter the string with punctuations :- ")
print(string)
punctuations = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
for i in string:
    if i in punctuations:
        string = string.replace(i,'')
print("The String without punctuation is :- \n",string)
        

Enter the string with punctuations :- "#I'm Adityaraj!%^&><"
"#I'm Adityaraj!%^&><"
The String without punctuation is :- 
 ImAdityaraj
