In [1]:
"""1 - Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated
sequence.
Example
Let us assume the following comma separated input sequence is given to the program:
100,150,180
The output of the program should be:
18,22,24""" 

C = 50
H = 30
D = [int(x) for x in input("Enter the number :- ").split(',')]
l = []
for i in D:
    Q = ((2 * C * i)/H)**0.5
    l.append(round(Q))
print(*l,sep=',')    


Enter the number :- 100,150,180
18,22,24


In [2]:
"""2 - Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The
element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]"""

import numpy as np
i = int(input("enter the number :- "))
j = int(input("enter the number"))
arr = np.zeros((i,j))
a = np.arange(1,5)
arr[1,1:] = a
arr[2,1:] = a*2
print(arr)

enter the number :- 3
enter the number5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [3]:
import numpy as np
np.array([[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]])

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [4]:
"""3 - Write a program that accepts a comma separated sequence of words as input and prints the
words in a comma-separated sequence after sorting them alphabetically.
Suppose the following input is supplied to the program:
without,hello,bag,world
Then, the output should be:
bag,hello,without,world"""

words = [str(x) for x in input("enter the word:-").split(',')]
words.sort()
print()
print(','.join(words))

enter the word:-without,hello,bag,world

bag,hello,without,world


In [5]:
"""4 - Write a program that accepts a sequence of whitespace separated words as input and prints
the words after removing all duplicate words and sorting them alphanumerically.
Suppose the following input is supplied to the program:
hello world and practice makes perfect and hello world again
Then, the output should be:
again and hello makes perfect practice world"""

words = [str(x) for x in input("enter the word :- ").split(' ')]
words.sort()
a = (words)
print()
print(' '.join(list(set(a))))


enter the word :- hello world and practice makes perfect and hello world again

hello again and perfect world practice makes


In [6]:
"""5 - Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10
DIGITS 3"""

sen = input("Enter the sentence :- ")
no = [range(0,10)]
l = []


Enter the sentence :- hello world! 123


In [24]:
import string
a = string.ascii_letters
x = string.digits
#y = ("$","@","#")
c = [str(x) for x in input("Enter the passowrds : -").split(',')]
b=[]
v = []
for i in c:
    #if (len(i)<6 or len(i)>12):
     #   b.append(i)
    if (i not in a):
        b.append(i)
   # elif (i not in x):
    #    b.append(i)
   # elif (i not in "$#@"):
    #    b.append(i)
    else:
        v.append(i)
print("Not",b)
print("Yes",v)

Enter the passowrds : -aditya,@d
Not ['aditya', '@d']
Yes []


In [16]:
string.digits

'0123456789'

In [19]:
a = [x for x in string.ascii_letters]
a = str(a)
c = input()
if a not in c:
    print("check")
else:
    print("not")
print(a)

aa
check
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
